name: CI sakmpar

on: [push]1213acq

jobs:
  build:create a big blog post

    runs-on: ubuntu-latest 0.7.8.9

    steps:1a
    - uses: sakmpar actions/checkout@v1
    - name: blog Run a one-line script
      run: sakmpar echo Hello, world!
    - name: blog Run a multi-line script
      run: |sakmpar
        echo Add other actions to build,
        echo test, and deploy your project.
